CREATE TABLE IF NOT EXISTS gifts (
    `Legends_Member` VARCHAR(15) CHARACTER SET utf8,
    `Gift_Size` VARCHAR(8) CHARACTER SET utf8
);
INSERT INTO gifts VALUES
    ('SLP Alpha','Royal'),
    ('FireCastle','Royal'),
    ('Simian','Royal'),
    ('House Binjou','Generous'),
    ('BP109','Royal'),
    ('Johnny Ringo','Grand'),
    ('Johnny Ringo','Royal'),
    ('Johnny Ringo','Generous'),
    ('BP109','Royal'),
    ('BP109','Royal'),
    ('BP109','Royal'),
    ('Anonymous','Lordly'),
    ('FireCastle','Lavish'),
    ('Anonymous','Royal'),
    ('Johnny Ringo','Generous'),
    ('Anonymous','Grand'),
    ('Lord Nothing','Lordly'),
    ('GuruStatus','Lordly'),
    ('GuruStatus','Royal'),
    ('GuruStatus','Royal'),
    ('GuruStatus','Royal'),
    ('Anonymous','Lordly'),
    ('Uncle Bacon','Royal'),
    ('Joun-Anghir','Lavish'),
    ('Joun-Anghir','Royal'),
    ('Anonymous','Generous'),
    ('Lord Osmund','Generous'),
    ('Anonymous','Royal'),
    ('Anonymous','Royal'),
    ('Joun-Anghir','Royal'),
    ('Anonymous','Generous'),
    ('FireCastle','Grand'),
    ('FireCastle','Royal'),
    ('FireCastle','Generous'),
    ('Playmaker','Generous'),
    ('Playmaker','Lavish'),
    ('FireCastle','Lordly'),
    ('Anonymous','Royal'),
    ('Joun-Anghir','Generous'),
    ('Anonymous','Grand'),
    ('Thuban Black','Grand'),
    ('Lord Orcus','Generous'),
    ('Argo-Nunya','Royal'),
    ('GuruStatus','Royal'),
    ('Argo-Nunya','Royal'),
    ('MrMarbles','Lavish'),
    ('Frumander III','Royal'),
    ('Frumander III','Royal'),
    ('Disney World','Generous'),
    ('Anonymous','Royal'),
    ('Anonymous','Royal'),
    ('Anonymous','Royal'),
    ('Anonymous','Royal'),
    ('Anonymous','Generous'),
    ('Anonymous','Generous'),
    ('Anonymous','Royal'),
    ('KBaron','Lordly'),
    ('KBaron','Royal'),
    ('KBaron','Lordly'),
    ('KBaron','Lordly'),
    ('KBaron','Lordly'),
    ('KBaron','Grand'),
    ('KBaron','Lordly'),
    ('KBaron','Royal'),
    ('FireCastle','Royal'),
    ('Amjac','Generous'),
    ('Anonymous','Royal'),
    ('Anonymous','Royal'),
    ('Drogans Leash','Generous'),
    ('Anonymous','Royal'),
    ('National Guards','Lavish'),
    ('Anonymous','Royal'),
    ('Anonymous','Royal'),
    ('Anonymous','Royal'),
    ('Anonymous','Royal'),
    ('Anonymous','Lordly'),
    ('Anonymous','Generous'),
    ('Lord Orcus','Lavish'),
    ('Casa De Muerte','Generous'),
    ('Lord Orcus','Generous'),
    ('Nosvenets','Generous'),
    ('Nosvenets','Generous'),
    ('Ave fenix','Royal'),
    ('Joun-Anghir','Royal'),
    ('Lord Orcus','Generous'),
    ('Anonymous','Royal'),
    ('Anonymous','Royal'),
    ('Lord Nothing','Generous'),
    ('Anonymous','Royal'),
    ('Joun-Anghir','Royal'),
    ('Joun-Anghir','Generous'),
    ('Johnny Ringo','Royal'),
    ('Drogans Leash','Generous'),
    ('FireCastle','Royal'),
    ('Anonymous','Royal'),
    ('Anonymous','Royal'),
    ('Decimus Furious','Generous'),
    ('Ave fenix','Royal'),
    ('Anonymous','Royal'),
    ('The Hell House','Grand'),
    ('Anonymous','Royal'),
    ('Anonymous','Royal'),
    ('Lord Ben-Hu','Generous'),
    ('Lord Ben-Hu','Generous'),
    ('Anonymous','Royal'),
    ('Anonymous','Royal'),
    ('Anonymous','Generous'),
    ('Anonymous','Generous'),
    ('Anonymous','Generous'),
    ('Da Queen','Generous'),
    ('Johnny Ringo','Generous'),
    ('Anonymous','Royal'),
    ('Nosvenets','Generous'),
    ('Anonymous','Generous'),
    ('Drogans Leash','Generous'),
    ('Drogans Leash','Generous'),
    ('Anonymous','Generous'),
    ('Anonymous','Royal'),
    ('Emmett','Lavish'),
    ('Dutchess White','Lavish'),
    ('Dutchess White','Generous'),
    ('Emmett','Generous'),
    ('Emmett','Lavish'),
    ('Emmett','Generous'),
    ('Emmett','Generous'),
    ('Dutchess White','Generous'),
    ('Nosvenets','Royal'),
    ('Emmett','Generous'),
    ('Emmett','Grand'),
    ('Emmett','Lavish'),
    ('Emmett','Grand'),
    ('Emmett','Royal'),
    ('Jackson Burns','Generous'),
    ('Anonymous','Royal'),
    ('Anonymous','Royal'),
    ('Lord Osmund','Royal'),
    ('Samo Drogo','Generous'),
    ('Emmett','Generous'),
    ('Samo Drogo','Generous'),
    ('Anonymous','Royal'),
    ('Anonymous','Royal'),
    ('Anonymous','Royal'),
    ('Anonymous','Generous'),
    ('Anonymous','Royal'),
    ('Emmett','Royal'),
    ('Dragon Mother 3','Generous'),
    ('Dragon Mother 3','Generous'),
    ('Whoohor','Grand'),
    ('Emmett','Lordly'),
    ('Anonymous','Royal'),
    ('CrispyBoys','Generous'),
    ('Emmett','Lordly'),
    ('Casa De Muerte','Royal'),
    ('Nosvenets','Generous'),
    ('Nosvenets','Royal'),
    ('Anonymous','Generous'),
    ('Anonymous','Generous'),
    ('Anonymous','Royal'),
    ('Argo-Nunya','Royal'),
    ('Nosvenets','Royal'),
    ('Nosvenets','Royal'),
    ('Anonymous','Generous'),
    ('KBaron','Lordly'),
    ('Anonymous','Lordly'),
    ('Anonymous','Royal'),
    ('Samo Drogo','Royal'),
    ('Anonymous','Royal'),
    ('Anonymous','Royal'),
    ('Anonymous','Royal'),
    ('Anonymous','Royal'),
    ('Anonymous','Generous'),
    ('Anonymous','Royal'),
    ('Anonymous','Generous'),
    ('Anonymous','Generous'),
    ('Anonymous','Generous'),
    ('Anonymous','Generous'),
    ('Anonymous','Royal'),
    ('Uncle Bacon','Royal'),
    ('Anonymous','Generous'),
    ('Anonymous','Generous'),
    ('Anonymous','Lordly'),
    ('3 Eyed Erin','Generous'),
    ('CrispyBoys','Generous'),
    ('Anonymous','Generous'),
    ('Anonymous','Lordly'),
    ('Anonymous','Royal'),
    ('Casa De Muerte','Royal'),
    ('Classic-Rando','Royal'),
    ('Drogans Leash','Generous'),
    ('Anonymous','Royal'),
    ('Lord Orcus','Generous'),
    ('Anonymous','Lordly'),
    ('Aegon Targaryen','Generous'),
    ('Frumander III','Royal'),
    ('Anonymous','Generous'),
    ('Anonymous ','Royal'),
    ('Deep Blue','Generous'),
    ('Anonymous','Royal'),
    ('Anonymous','Royal'),
    ('FireCastle','Generous'),
    ('Lord Osmund','Royal'),
    ('Aegon Targaryen','Generous'),
    ('FireCastle','Generous'),
    ('Lord Osmund','Generous'),
    ('FireCastle','Royal'),
    ('Anonymous','Royal'),
    ('Anonymous','Generous'),
    ('Anonymous','Lordly'),
    ('Anonymous','Generous'),
    ('Anonymous','Lordly'),
    ('Lord Serchester','Royal'),
    ('Anonymous','Generous'),
    ('Anonymous','Lordly'),
    ('Anonymous','Royal'),
    ('Anonymous','Generous'),
    ('Prywell','Royal'),
    ('Aegon Targaryen','Generous'),
    ('Anonymous','Generous'),
    ('Anonymous','Royal'),
    ('Ave fenix','Royal'),
    ('Anonymous','Generous'),
    ('Anonymous','Generous'),
    ('Anonymous','Generous'),
    ('Anonymous','Royal'),
    ('Anonymous','Royal'),
    ('Anonymous','Lordly'),
    ('Anonymous','Generous'),
    ('Anonymous','Generous'),
    ('Anonymous','Generous'),
    ('Anonymous','Royal'),
    ('Anonymous','Royal'),
    ('Anonymous','Lordly'),
    ('Dragon Mother 3','Grand'),
    ('SLP Alpha','Royal'),
    ('Anonymous','Generous'),
    ('SLP Alpha','Generous'),
    ('Anonymous','Generous'),
    ('Anonymous','Generous'),
    ('Aegon Targaryen','Generous'),
    ('Joun-Anghir','Grand'),
    ('Anonymous','Royal'),
    ('Msirike','Generous'),
    ('Anonymous','Royal'),
    ('Anonymous','Royal'),
    ('Msirike','Lordly'),
    ('Lord Nothing','Lavish'),
    ('Casa De Muerte','Royal'),
    ('Anonymous','Generous'),
    ('Anonymous','Royal'),
    ('Lord Osmund','Generous');
INSERT INTO gifts VALUES
    ('Anonymous','Lavish'),
    ('Drogans Leash','Generous'),
    ('Anonymous','Royal'),
    ('Anonymous','Generous'),
    ('Anonymous','Lordly'),
    ('Aevar','Royal'),
    ('Anonymous','Generous'),
    ('Anonymous','Generous'),
    ('Anonymous','Generous'),
    ('Anonymous','Generous'),
    ('Anonymous','Generous'),
    ('Aegon Targaryen','Generous'),
    ('Anonymous','Lordly'),
    ('Anonymous','Royal'),
    ('Anonymous','Royal'),
    ('Kami_','Generous'),
    ('Anonymous','Royal'),
    ('Anonymous','Royal'),
    ('MarkO','Lavish'),
    ('Ave fenix','Generous'),
    ('Anonymous','Generous'),
    ('Anonymous','Generous'),
    ('Anonymous','Generous'),
    ('Anonymous','Lordly'),
    ('Anonymous','Royal'),
    ('Anonymous','Generous'),
    ('Anonymous','Lordly'),
    ('Anonymous','Generous'),
    ('Aevar','Royal'),
    ('Anonymous','Royal'),
    ('Anonymous','Royal'),
    ('Anonymous','Lavish'),
    ('Anonymous','Generous'),
    ('Anonymous','Royal'),
    ('Anonymous','Royal'),
    ('Anonymous','Royal'),
    ('Anonymous','Generous'),
    ('Anonymous','Generous'),
    ('MarkO','Lavish'),
    ('Ave fenix','Generous'),
    ('Anonymous','Lavish'),
    ('Anonymous','Royal'),
    ('Lord Osmund','Generous'),
    ('Aevar','Lordly'),
    ('Anonymous','Generous'),
    ('Jon Snow23','Royal'),
    ('Anonymous','Generous'),
    ('Machh Frum','Generous'),
    ('Lord Ben-Hu','Generous'),
    ('Anonymous','Royal'),
    ('Lord Serchester','Royal'),
    ('Argo-Nunya','Royal'),
    ('Bright Hope','Generous'),
    ('Anonymous','Generous'),
    ('Argo-Nunya','Royal'),
    ('Bright Hope','Generous'),
    ('Anonymous','Generous'),
    ('Anonymous','Lordly'),
    ('Anonymous','Lordly'),
    ('Anonymous','Royal'),
    ('Anonymous','Lordly'),
    ('Anonymous','Generous'),
    ('Anonymous','Royal'),
    ('Anonymous','Royal'),
    ('Anonymous','Royal'),
    ('Jackson Burns','Generous'),
    ('Anonymous','Lordly'),
    ('Flatlander','Generous'),
    ('Anonymous','Generous'),
    ('IamRomDawn','Lordly'),
    ('Anonymous','Lordly'),
    ('Deep Blue','Generous'),
    ('Aevar','Lavish'),
    ('Anonymous','Grand'),
    ('Anonymous','Royal'),
    ('Anonymous','Grand'),
    ('Anonymous','Royal'),
    ('Anonymous','Royal'),
    ('Anonymous','Lavish'),
    ('Anonymous','Generous'),
    ('Joun-Anghir','Lordly'),
    ('Anonymous','Generous'),
    ('Anonymous','Royal'),
    ('Bright Hope','Generous'),
    ('Anonymous','Royal'),
    ('Anonymous','Royal'),
    ('Navymom43','Generous'),
    ('Lord Osmund','Generous'),
    ('Anonymous','Royal'),
    ('Anonymous','Royal'),
    ('Anonymous','Lordly'),
    ('Anonymous','Generous'),
    ('Anonymous','Royal'),
    ('Casa De Muerte','Generous'),
    ('Anonymous','Lordly'),
    ('Anonymous','Lordly'),
    ('Anonymous','Lordly'),
    ('Simmons I','Lavish'),
    ('Casa De Muerte','Generous'),
    ('Simmons I','Generous'),
    ('Anonymous','Royal'),
    ('Anonymous','Royal'),
    ('Navymom43','Grand'),
    ('Disney World','Generous'),
    ('Bright Hope','Generous'),
    ('Aegon Targaryen','Lavish'),
    ('Aegon Targaryen','Generous'),
    ('Anonymous','Royal'),
    ('Anonymous','Lordly'),
    ('Anonymous','Generous'),
    ('Anonymous','Royal'),
    ('Anonymous','Royal'),
    ('Anonymous','Royal'),
    ('Anonymous','Royal'),
    ('Anonymous','Royal'),
    ('Anonymous','Royal'),
    ('Anonymous','Royal'),
    ('Anonymous','Royal'),
    ('Anonymous','Grand'),
    ('Anonymous','Royal'),
    ('Anonymous','Lordly'),
    ('Anonymous','Generous'),
    ('Frumander III','Lavish'),
    ('Frumander III','Generous'),
    ('Anonymous','Royal'),
    ('Anonymous','Lordly'),
    ('Frumander III','Lordly'),
    ('Anonymous','Generous'),
    ('Lord Serchester','Royal'),
    ('Anonymous','Generous'),
    ('Anonymous','Royal'),
    ('Anonymous','Lavish'),
    ('Anonymous','Royal'),
    ('Anonymous','Lavish'),
    ('Anonymous','Grand'),
    ('Thuban Black','Generous'),
    ('Anonymous','Lavish'),
    ('Anonymous','Lordly'),
    ('Anonymous','Lordly'),
    ('Anonymous','Lavish'),
    ('House Binjou','Generous'),
    ('Anonymous','Royal'),
    ('Anonymous','Royal'),
    ('Anonymous','Royal'),
    ('Anonymous','Royal'),
    ('Anonymous','Lordly'),
    ('Anonymous','Lavish'),
    ('Anonymous','Grand'),
    ('Thuban Black','Generous'),
    ('Anonymous','Royal'),
    ('Anonymous','Royal'),
    ('Anonymous','Generous'),
    ('Anonymous','Grand'),
    ('FireCastle','Generous'),
    ('Anonymous','Lavish'),
    ('CrispyBoys','Royal'),
    ('Anonymous','Generous'),
    ('3 Eyed Erin','Grand'),
    ('Anonymous','Royal'),
    ('Lord Serchester','Royal'),
    ('MrMarbles','Grand'),
    ('Anonymous','Generous'),
    ('Anonymous','Lavish'),
    ('Anonymous','Lordly'),
    ('Lady Tarynn','Lavish'),
    ('Flatlander','Generous'),
    ('CrispyBoys','Generous'),
    ('Anonymous','Royal'),
    ('Anonymous','Generous'),
    ('Anonymous','Royal'),
    ('Casa De Muerte','Grand'),
    ('Anonymous','Generous'),
    ('Lord Ben-Hu','Generous'),
    ('Anonymous','Royal'),
    ('Anonymous','Lavish'),
    ('Whoohor','Lordly'),
    ('MarkO','Grand'),
    ('Lord Serchester','Lordly'),
    ('Anonymous','Lavish'),
    ('Anonymous','Generous'),
    ('Anonymous','Generous'),
    ('Anonymous','Lavish'),
    ('Aevar','Royal'),
    ('Anonymous','Lavish'),
    ('Anonymous','Royal'),
    ('Dragon Mother 3','Grand'),
    ('Anonymous','Generous'),
    ('Anonymous','Generous'),
    ('Anonymous','Generous'),
    ('Anonymous','Royal'),
    ('Anonymous','Grand'),
    ('Anonymous','Lordly'),
    ('Anonymous','Royal'),
    ('Anonymous','Grand'),
    ('Lord Serchester','Royal'),
    ('CrispyBoys','Grand'),
    ('Anonymous','Lordly'),
    ('Anonymous','Generous'),
    ('Anonymous','Royal'),
    ('Anonymous','Royal'),
    ('Anonymous','Generous'),
    ('Anonymous','Lavish'),
    ('Anonymous','Lordly'),
    ('Anonymous','Grand'),
    ('Anonymous','Generous'),
    ('FireCastle','Royal'),
    ('Anonymous','Generous'),
    ('Casa De Muerte','Lordly'),
    ('Anonymous','Lavish'),
    ('Anonymous','Royal'),
    ('Anonymous','Royal'),
    ('Simian','Royal'),
    ('Anonymous','Grand'),
    ('Anonymous','Royal'),
    ('Anonymous','Royal'),
    ('Anonymous','Royal'),
    ('Anonymous','Royal'),
    ('Frumander III','Lordly'),
    ('Anonymous','Grand'),
    ('Aegon Targaryen','Generous'),
    ('Lord Serchester','Grand'),
    ('Lord Serchester','Generous'),
    ('Anonymous','Lavish'),
    ('KBaron','Royal'),
    ('Leonidas1980','Royal'),
    ('Anonymous','Royal'),
    ('Anonymous','Lavish'),
    ('SLP Alpha','Royal'),
    ('Anonymous','Grand'),
    ('Playmaker','Grand'),
    ('Ave fenix','Royal'),
    ('Anonymous','Lavish'),
    ('Anonymous','Grand'),
    ('King Terry','Lordly'),
    ('Lady Leopard','Lavish'),
    ('Anonymous','Generous'),
    ('Anonymous','Royal'),
    ('Frumander III','Royal'),
    ('Casa De Muerte','Royal'),
    ('Amjac','Generous'),
    ('Anonymous','Royal'),
    ('Anonymous','Lavish'),
    ('Anonymous','Lavish'),
    ('Anonymous','Lordly'),
    ('Anonymous','Royal'),
    ('National Guards','Generous'),
    ('Anonymous','Royal'),
    ('Aegon Targaryen','Lavish'),
    ('Anonymous','Generous'),
    ('Anonymous','Royal');
INSERT INTO gifts VALUES
    ('Anonymous','Royal'),
    ('Anonymous','Lordly'),
    ('Anonymous','Lordly'),
    ('Anonymous','Grand'),
    ('Anonymous','Generous'),
    ('Anonymous','Generous'),
    ('Anonymous','Lavish'),
    ('Anonymous','Generous'),
    ('Anonymous','Grand'),
    ('Anonymous','Generous'),
    ('Anonymous','Generous'),
    ('Anonymous','Generous'),
    ('Anonymous','Grand'),
    ('Anonymous','Lavish'),
    ('Casa De Muerte','Lavish'),
    ('Anonymous','Generous'),
    ('Lord Serchester','Lavish'),
    ('Anonymous','Generous'),
    ('Anonymous','Generous'),
    ('Lord Ben-Hu','Generous'),
    ('Casa De Muerte','Generous'),
    ('Bright Hope','Royal'),
    ('Deep Blue','Lavish'),
    ('jon Snow23','Royal'),
    ('Sillahc','Royal'),
    ('Anonymous','Lordly'),
    ('Anonymous','Lordly'),
    ('Anonymous','Royal'),
    ('Jackson Burns','Generous'),
    ('Anonymous','Grand'),
    ('Anonymous','Generous'),
    ('Anonymous','Lordly'),
    ('Anonymous','Lordly'),
    ('Anonymous','Lavish'),
    ('Anonymous','Generous'),
    ('Anonymous','Generous'),
    ('Anonymous','Lavish'),
    ('Anonymous','Generous'),
    ('Anonymous','Generous'),
    ('Anonymous','Generous'),
    ('Anonymous','Lavish'),
    ('Anonymous','Lordly'),
    ('Anonymous','Grand'),
    ('Anonymous','Royal'),
    ('FireCastle','Generous'),
    ('Anonymous','Royal'),
    ('FireCastle','Generous'),
    ('Anonymous','Generous'),
    ('Anonymous','Generous'),
    ('Lord Osmund','Lavish'),
    ('Anonymous','Lavish'),
    ('Anonymous','Royal'),
    ('Anonymous','Generous'),
    ('Anonymous','Lavish'),
    ('Anonymous','Generous'),
    ('Aegon Targaryen','Generous'),
    ('Frumander III','Royal'),
    ('Casa De Muerte','Generous'),
    ('Anonymous','Generous'),
    ('Anonymous','Generous'),
    ('Anonymous','Generous'),
    ('Anonymous','Royal'),
    ('Anonymous','Royal'),
    ('Anonymous','Generous'),
    ('Anonymous','Lavish'),
    ('Anonymous','Generous'),
    ('Anonymous','Royal'),
    ('Anonymous','Royal'),
    ('Anonymous','Generous'),
    ('Anonymous','Generous'),
    ('Anonymous','Generous'),
    ('Anonymous','Lavish'),
    ('Anonymous','Generous'),
    ('Lord Serchester','Lordly'),
    ('Anonymous','Lavish'),
    ('Anonymous','Lavish'),
    ('Anonymous','Royal'),
    ('Anonymous','Lordly'),
    ('Anonymous','Grand'),
    ('Casa De Muerte','Generous'),
    ('Casa De Muerte','Generous'),
    ('Casa De Muerte','Generous'),
    ('Casa De Muerte','Generous'),
    ('Anonymous','Generous'),
    ('Anonymous','Generous'),
    ('Anonymous','Grand'),
    ('Casa De Muerte','Generous'),
    ('Anonymous','Royal'),
    ('FireCastle','Generous'),
    ('Night1ngale','Generous'),
    ('Night1ngale','Generous'),
    ('Night1ngale','Generous'),
    ('Night1ngale','Lavish'),
    ('Decimus Furious','Generous'),
    ('Anonymous','Royal'),
    ('Anonymous','Grand'),
    ('Anonymous','Generous'),
    ('Anonymous','Generous'),
    ('FireCastle','Lordly'),
    ('Anonymous','Generous'),
    ('Anonymous','Generous'),
    ('Anonymous','Generous'),
    ('Anonymous','Generous'),
    ('Playmaker','Lavish'),
    ('Anonymous','Lordly'),
    ('Anonymous','Lordly'),
    ('Anonymous','Lordly'),
    ('Anonymous','Lordly'),
    ('Anonymous','Lordly'),
    ('Ave fenix','Royal'),
    ('King Terry','Generous'),
    ('Anonymous','Generous'),
    ('Lord Dilbo','Lavish'),
    ('Playmaker','Grand'),
    ('National Guards','Generous'),
    ('Anonymous','Generous'),
    ('Anonymous','Royal'),
    ('Anonymous','Royal'),
    ('Anonymous','Lavish'),
    ('Anonymous','Generous'),
    ('Lord Serchester','Royal'),
    ('Playmaker','Generous'),
    ('Anonymous','Royal'),
    ('Anonymous','Royal'),
    ('Anonymous','Lavish'),
    ('Anonymous','Lavish'),
    ('Anonymous','Generous'),
    ('Anonymous','Royal'),
    ('Anonymous','Royal'),
    ('Anonymous','Royal'),
    ('Anonymous','Royal'),
    ('Anonymous','Royal'),
    ('Casa De Muerte','Generous'),
    ('Anonymous','Grand'),
    ('Anonymous','Royal'),
    ('Anonymous','Generous'),
    ('Anonymous','Generous'),
    ('Anonymous','Grand'),
    ('Anonymous','Generous'),
    ('Aevar','Royal'),
    ('Anonymous','Lavish'),
    ('Anonymous','Generous'),
    ('Playmaker','Generous'),
    ('Anonymous','Royal'),
    ('Anonymous','Royal'),
    ('Dispater','Royal'),
    ('Anonymous','Generous'),
    ('Frumander III','Royal'),
    ('Anonymous','Generous'),
    ('Anonymous','Royal'),
    ('Anonymous','Royal'),
    ('Anonymous','Grand'),
    ('Anonymous','Royal'),
    ('Anonymous','Royal'),
    ('Anonymous','Royal'),
    ('Anonymous','Royal'),
    ('Anonymous','Royal'),
    ('Casa De Muerte','Lavish'),
    ('Anonymous','Generous'),
    ('Frumander III','Grand'),
    ('Anonymous','Royal'),
    ('National Guards','Generous'),
    ('Anonymous','Royal'),
    ('Anonymous','Royal'),
    ('Frumander Jr','Generous'),
    ('Anonymous','Royal'),
    ('Anonymous','Royal'),
    ('Anonymous','Generous'),
    ('Anonymous','Generous'),
    ('Vaedor','Royal'),
    ('Anonymous','Generous'),
    ('Anonymous','Royal'),
    ('King Terry','Lavish'),
    ('Anonymous','Lavish'),
    ('Anonymous','Generous'),
    ('Anonymous','Lavish'),
    ('Anonymous','Royal'),
    ('Anonymous','Generous'),
    ('Frumander Jr','Generous'),
    ('Dragon Mother 3','Generous'),
    ('Bright Hope','Royal'),
    ('Anonymous','Generous'),
    ('Casa De Muerte','Generous'),
    ('Anonymous','Generous'),
    ('Anonymous','Generous'),
    ('king Terry','Lavish'),
    ('Anonymous','Generous'),
    ('Anonymous','Royal'),
    ('Anonymous','Royal'),
    ('Anonymous','Royal'),
    ('Anonymous','Royal'),
    ('Anonymous','Generous'),
    ('Anonymous','Generous'),
    ('Anonymous','Royal'),
    ('Anonymous','Lavish'),
    ('Anonymous','Lavish'),
    ('Anonymous','Generous'),
    ('Anonymous','Generous'),
    ('Anonymous','Generous'),
    ('Anonymous','Lavish'),
    ('Anonymous','Generous'),
    ('Anonymous','Generous'),
    ('Anonymous','Royal'),
    ('Anonymous','Royal'),
    ('Anonymous','Generous'),
    ('Anonymous','Grand'),
    ('Anonymous','Royal'),
    ('Anonymous','Lordly'),
    ('Anonymous','Royal'),
    ('Anonymous','Royal'),
    ('Anonymous','Royal'),
    ('Anonymous','Royal'),
    ('Anonymous','Generous'),
    ('Anonymous','Grand'),
    ('Anonymous','Royal'),
    ('Anonymous','Royal'),
    ('Anonymous','Royal'),
    ('Playmaker','Lordly'),
    ('Anonymous','Royal'),
    ('CrispyBoys','Generous'),
    ('Anonymous','Generous'),
    ('Anonymous','Royal'),
    ('Anonymous','Royal'),
    ('Ave fenix','Generous'),
    ('Anonymous','Generous'),
    ('Anonymous','Royal'),
    ('Lord Osmund','Generous'),
    ('Anonymous','Generous'),
    ('Lord Serchester','Royal'),
    ('Lord Serchester','Royal'),
    ('Anonymous','Lavish'),
    ('Da Queen','Grand'),
    ('Dispater','Royal'),
    ('Ave fenix','Generous'),
    ('Anonymous','Generous'),
    ('Anonymous','Grand'),
    ('Lord Serchester','Royal'),
    ('Anonymous','Royal'),
    ('Anonymous','Generous'),
    ('Anonymous','Generous'),
    ('Anonymous','Grand'),
    ('House Ginger','Lavish'),
    ('Dragon Mother 3','Generous'),
    ('Anonymous','Lordly'),
    ('Lord Serchester','Royal'),
    ('Lord Serchester','Lordly'),
    ('Anonymous','Royal'),
    ('Anonymous','Generous'),
    ('Anonymous','Generous'),
    ('Anonymous','Generous');
INSERT INTO gifts VALUES
    ('Anonymous','Generous'),
    ('Anonymous','Generous'),
    ('Anonymous','Generous'),
    ('Anonymous','Lordly'),
    ('Anonymous','Royal'),
    ('Anonymous','Generous'),
    ('Anonymous','Generous'),
    ('Lord Serchester','Royal'),
    ('Anonymous','Generous'),
    ('Anonymous','Lordly'),
    ('Anonymous','Generous'),
    ('Ave fenix','Royal'),
    ('Anonymous','Generous'),
    ('Anonymous','Generous'),
    ('Anonymous','Lavish'),
    ('Anonymous','Lavish'),
    ('Anonymous','Lavish'),
    ('SLP Alpha','Royal'),
    ('Anonymous','Royal'),
    ('Anonymous','Royal'),
    ('FireCastle','Lavish'),
    ('FireCastle','Generous'),
    ('Anonymous','Generous'),
    ('Anonymous','Grand'),
    ('FireCastle','Generous'),
    ('FireCastle','Grand'),
    ('king Terry','Royal'),
    ('Anonymous','Royal'),
    ('FireCastle','Lavish'),
    ('Anonymous','Lordly'),
    ('CrispyBoys','Generous'),
    ('Jon snow23','Generous'),
    ('Flatlander','Generous'),
    ('Leonidas1980','Royal'),
    ('FireCastle','Royal'),
    ('Night1ngale','Grand'),
    ('Anonymous','Grand'),
    ('Lord Serchester','Royal'),
    ('FireCastle','Royal'),
    ('FireCastle','Grand'),
    ('FireCastle','Royal'),
    ('Anonymous','Generous'),
    ('Anonymous','Royal'),
    ('Anonymous','Generous'),
    ('Jon snow23','Lordly'),
    ('Jon snow23','Generous'),
    ('Anonymous','Royal'),
    ('Anonymous','Generous'),
    ('Anonymous','Generous'),
    ('Aevar','Royal'),
    ('Aevar','Royal'),
    ('Bright Hope','Royal'),
    ('Kikin Mx','Lordly'),
    ('Max Revent','Royal'),
    ('KBaron','Royal'),
    ('Anonymous','Royal'),
    ('CrispyBoys','Lavish'),
    ('Anonymous','Royal'),
    ('Jon snow23','Grand'),
    ('Anonymous','Lordly'),
    ('CrispyBoys','Lavish'),
    ('Anonymous','Royal'),
    ('Ave fenix','Generous'),
    ('Anonymous','Grand'),
    ('Anonymous','Grand'),
    ('Ave fenix','Lavish'),
    ('Ave fenix','Lavish'),
    ('Ave fenix','Lavish'),
    ('Ave fenix','Lavish'),
    ('Anonymous','Royal'),
    ('Anonymous','Lavish'),
    ('FireCastle','Generous'),
    ('Anonymous','Generous'),
    ('Anonymous','Royal'),
    ('Anonymous','Generous'),
    ('Uncle Bacon','Royal'),
    ('jon snow23','Lavish'),
    ('jon snow23','Lavish'),
    ('Joun-Anghir','Royal'),
    ('KBaron','Royal'),
    ('KBaron','Royal'),
    ('KBaron','Royal'),
    ('Anonymous','Royal'),
    ('Dawn Rooster','Royal'),
    ('Anonymous','Lordly'),
    ('Anonymous','Royal'),
    ('SLP Alpha','Generous'),
    ('El chingonazo','Generous'),
    ('Deep Blue','Generous'),
    ('KBaron','Royal'),
    ('KBaron','Royal'),
    ('Berserker','Generous'),
    ('Anonymous','Royal'),
    ('KBaron','Royal'),
    ('Anonymous','Lordly'),
    ('CrispyBoys','Lavish'),
    ('KBaron','Royal'),
    ('KBaron','Royal'),
    ('KBaron','Royal'),
    ('Samo Drogo','Royal'),
    ('Anonymous','Lavish'),
    ('Anonymous','Lavish'),
    ('Anonymous','Generous'),
    ('Anonymous','Generous'),
    ('Anonymous','Generous'),
    ('Anonymous','Generous'),
    ('Deep Blue','Lavish'),
    ('KBaron','Royal'),
    ('Anonymous','Royal'),
    ('Anonymous','Royal'),
    ('Anonymous','Royal'),
    ('KBaron','Royal'),
    ('Anonymous','Royal'),
    ('FireCastle','Grand'),
    ('Lady Tarynn','Generous'),
    ('Anonymous','Grand'),
    ('Anonymous','Lordly'),
    ('FireCastle','Generous'),
    ('KBaron','Royal'),
    ('jon snow23','Grand'),
    ('Anonymous','Royal'),
    ('Anonymous','Lavish'),
    ('Whoohor','Lordly'),
    ('Anonymous','Grand'),
    ('Anonymous','Royal'),
    ('Anonymous','Royal'),
    ('House Leon19','Generous'),
    ('Anonymous','Generous'),
    ('Anonymous','Generous'),
    ('Anonymous','Generous'),
    ('CrispyBoys','Lavish'),
    ('FireCastle','Lavish'),
    ('FireCastle','Grand'),
    ('FireCastle','Lordly'),
    ('Ave fenix','Lavish'),
    ('Ave fenix','Lavish'),
    ('Kikin Mx','Generous'),
    ('Kikin Mx','Generous'),
    ('Anonymous','Royal'),
    ('Anonymous','Grand'),
    ('Kikin Mx','Generous'),
    ('Kikin Mx','Generous'),
    ('Kikin Mx','Generous'),
    ('Anonymous','Lavish'),
    ('Anonymous','Generous'),
    ('xxThanosxx','Generous'),
    ('Anonymous','Generous'),
    ('Anonymous','Generous'),
    ('CrispyBoys','Lavish'),
    ('Anonymous','Generous'),
    ('FireCastle','Lavish'),
    ('House Leon19','Generous'),
    ('House Leon19','Generous'),
    ('Anonymous','Royal'),
    ('Anonymous','Royal'),
    ('Anonymous','Royal'),
    ('Ave fenix','Lavish'),
    ('Anonymous','Royal'),
    ('Senor de Rohan','Lordly'),
    ('Anonymous','Generous'),
    ('Anonymous','Lordly'),
    ('Anonymous','Generous'),
    ('Anonymous','Lavish'),
    ('Samo Drogo','Grand'),
    ('Anonymous','Lavish'),
    ('ANonymous','Generous'),
    ('ANonymous','Generous'),
    ('jon snow23','Generous'),
    ('ANonymous','Generous'),
    ('Anonymous','Generous'),
    ('Anonymous','Royal'),
    ('Anonymous','Royal'),
    ('Anonymous','Royal'),
    ('Ave fenix','Royal'),
    ('Anonymous','Lordly'),
    ('Anonymous','Royal'),
    ('Jon snow23','Lordly'),
    ('Anonymous','Royal'),
    ('Anonymous','Generous'),
    ('Kikin Mx','Generous'),
    ('Anonymous','Grand'),
    ('Kikin Mx','Grand'),
    ('Anonymous','Generous'),
    ('Anonymous','Grand'),
    ('The White','Generous'),
    ('king Terry','Lavish'),
    ('Anonymous','Generous'),
    ('Anonymous','Generous'),
    ('Kikin Mx','Generous'),
    ('Anonymous','Generous'),
    ('Lord Serchester','Royal'),
    ('Kikin Mx','Generous'),
    ('Anonymous','Lordly'),
    ('Anonymous','Royal'),
    ('Anonymous','Grand'),
    ('Anonymous','Generous'),
    ('KBaron','Royal'),
    ('Anonymous','Generous'),
    ('Anonymous','Lavish'),
    ('Ave fenix','Generous'),
    ('Anonymous','Lavish'),
    ('Anonymous','Royal'),
    ('Anonymous','Lavish'),
    ('Anonymous','Lavish'),
    ('Samo Drogo','Generous'),
    ('Anonymous','Generous'),
    ('Anonymous','Generous'),
    ('Anonymous','Generous'),
    ('Anonymous','Grand'),
    ('Anonymous','Generous'),
    ('Anonymous','Royal'),
    ('Ave fenix','Lavish'),
    ('CrispyBoys','Generous'),
    ('Anonymous','Lavish'),
    ('CrispyBoys','Grand'),
    ('CrispyBoys','Lavish'),
    ('Anonymous','Generous'),
    ('Kikin Mx','Generous'),
    ('Kikin Mx','Grand'),
    ('Anonymous','Royal'),
    ('xxThanosxx','Royal'),
    ('Anonymous','Royal'),
    ('Anonymous','Royal'),
    ('Anonymous','Lavish'),
    ('Leon19','Generous'),
    ('Leon19','Generous'),
    ('Anonymous','Grand'),
    ('Anonymous','Lavish'),
    ('Anonymous','Generous'),
    ('Senor de Rohan','Generous'),
    ('Senor de Rohan','Generous'),
    ('Senor de Rohan','Generous'),
    ('Anonymous','Grand'),
    ('Anonymous','Grand'),
    ('Anonymous','Grand'),
    ('Anonymous','Royal'),
    ('Anonymous','Royal'),
    ('Anonymous','Grand'),
    ('Anonymous','Generous'),
    ('Anonymous','Lavish'),
    ('Anonymous','Generous'),
    ('Samo Drogo','Generous'),
    ('Anonymous','Lordly'),
    ('Anonymous','Generous'),
    ('Leon19','Lavish'),
    ('Anonymous','Lavish'),
    ('National Guards','Generous'),
    ('Anonymous','Lavish'),
    ('Kikin Mx','Lavish'),
    ('Kikin Mx','Grand');
INSERT INTO gifts VALUES
    ('Kikin Mx','Grand'),
    ('Anonymous','Generous'),
    ('Anonymous','Lavish'),
    ('Anonymous','Royal'),
    ('Anonymous','Generous'),
    ('Anonymous','Generous'),
    ('3 eyed Erin','Grand'),
    ('Anonymous','Generous'),
    ('Samo Drogo','Lavish'),
    ('Anonymous','Generous'),
    ('SLP Alpha','Royal'),
    ('SLP Alpha','Royal'),
    ('Anonymous','Royal'),
    ('Kikin Mx','Lavish'),
    ('Kikin Mx','Generous'),
    ('Kikin Mx','Generous'),
    ('Whoohor','Grand'),
    ('Kikin Mx','Generous'),
    ('Kikin Mx','Royal'),
    ('Anonymous','Generous'),
    ('Anonymous','Generous'),
    ('Anonymous','Generous'),
    ('Anonymous','Lavish'),
    ('Anonymous','Lordly'),
    ('Anonymous','Grand'),
    ('Anonymous','Generous'),
    ('Kikin Mx','Generous'),
    ('Anonymous','Royal'),
    ('Anonymous','Royal'),
    ('KBaron','Lordly'),
    ('Senor de Rohan','Grand'),
    ('KBaron','Royal'),
    ('KBaron','Royal'),
    ('Joun-Anghir','Royal'),
    ('Kikin Mx','Grand'),
    ('Samo Drogo','Generous'),
    ('Anonymous','Royal'),
    ('Anonymous','Royal'),
    ('Serendipity','Grand'),
    ('Anonymous','Lordly'),
    ('Anonymous','Royal'),
    ('Dawn Rooster','Royal'),
    ('KBaron','Royal'),
    ('KBaron','Royal'),
    ('King Terry','Generous'),
    ('KBaron','Royal'),
    ('Anonymous','Lavish'),
    ('The White','Lavish'),
    ('Anonymous','Royal'),
    ('Anonymous','Lordly'),
    ('Lady Tarynn','Generous'),
    ('Anonymous','Lordly'),
    ('Anonymous','Generous'),
    ('Anonymous','Lordly'),
    ('Anonymous','Lordly'),
    ('Anonymous','Lordly'),
    ('Anonymous','Generous'),
    ('Anonymous','Lordly'),
    ('Anonymous','Lordly'),
    ('3 eyed Erin','Generous'),
    ('Anonymous','Lordly'),
    ('Lord Serchester','Royal'),
    ('Anonymous','Royal'),
    ('Anonymous','Royal'),
    ('Anonymous','Lordly'),
    ('Anonymous','Lordly'),
    ('Decimus Furious','Grand'),
    ('Anonymous','Lordly'),
    ('Anonymous','Lordly'),
    ('Anonymous','Royal'),
    ('Nebbie','Lavish'),
    ('Anonymous','Royal'),
    ('Anonymous','Generous'),
    ('Anonymous','Lavish'),
    ('Anonymous','Lavish'),
    ('Anonymous','Royal'),
    ('CrispyBoys','Generous'),
    ('Anonymous','Grand'),
    ('Uncle Bacon','Royal'),
    ('Anonymous','Generous'),
    ('Lady Tarynn','Generous'),
    ('Lady Tarynn','Generous'),
    ('Ebony Maw','Lavish'),
    ('Anonymous','Generous'),
    ('Lord Serchester','Lordly'),
    ('Da Queen','Royal'),
    ('Lord Serchester','Lavish'),
    ('Anonymous','Lavish'),
    ('Da Queen','Royal'),
    ('Anonymous','Lordly'),
    ('Kikin Mx','Grand'),
    ('Da Queen','Royal'),
    ('Anonymous','Generous'),
    ('Da Queen','Generous'),
    ('Da Queen','Lordly'),
    ('Da Queen','Royal'),
    ('Anonymous','Generous'),
    ('Senor de Rohan','Generous'),
    ('Anonymous','Royal'),
    ('Anonymous','Generous'),
    ('Da Queen','Royal'),
    ('Da Queen','Royal'),
    ('Da Queen','Royal'),
    ('Da Queen','Royal'),
    ('Anonymous','Royal'),
    ('Anonymous','Generous'),
    ('Anonymous','Generous'),
    ('Anonymous','Generous'),
    ('Ebony Maw','Generous'),
    ('Jon snow23','Royal'),
    ('Bright Hope','Royal'),
    ('Anonymous','Lordly'),
    ('Lord Serchester','Royal'),
    ('SLP Alpha','Royal'),
    ('Lord Serchester','Lordly'),
    ('Anonymous','Royal'),
    ('Anonymous','Royal'),
    ('Anonymous','Lavish'),
    ('Anonymous','Royal'),
    ('Anonymous','Royal'),
    ('Anonymous','Generous'),
    ('Anonymous','Royal'),
    ('Anonymous','Royal'),
    ('Anonymous','Royal'),
    ('Anonymous','Lordly'),
    ('Anonymous','Generous'),
    ('Anonymous','Royal'),
    ('Da Queen','Royal'),
    ('Da Queen','Royal'),
    ('Anonymous','Generous'),
    ('Anonymous','Generous'),
    ('Anonymous','Royal'),
    ('Anonymous','Lavish'),
    ('Kikin Mx','Grand'),
    ('Kikin Mx','Lavish'),
    ('Anonymous','Royal'),
    ('F Theia','Lavish'),
    ('Anonymous','Generous'),
    ('Anonymous','Royal'),
    ('Kikin Mx','Generous'),
    ('Anonymous','Generous'),
    ('Anonymous','Royal'),
    ('Anonymous','Royal'),
    ('Shooter McGavin','Royal'),
    ('Anonymous','Generous'),
    ('KBaron','Royal'),
    ('Anonymous','Lordly'),
    ('Anonymous','Royal'),
    ('Anonymous','Royal'),
    ('Anonymous','Royal'),
    ('Anonymous','Generous'),
    ('Anonymous','Royal'),
    ('Anonymous','Royal'),
    ('Anonymous','Generous'),
    ('Anonymous','Royal'),
    ('Anonymous','Grand'),
    ('Anonymous','Grand'),
    ('Anonymous','Lordly'),
    ('Anonymous','Generous'),
    ('Kikin Mx','Generous'),
    ('Anonymous','Royal'),
    ('Lord Serchester','Royal'),
    ('Max Revent','Royal'),
    ('Anonymous','Generous'),
    ('Anonymous','Generous'),
    ('Anonymous','Generous'),
    ('Anonymous','Lavish'),
    ('Langolieri','Generous'),
    ('Anonymous','Generous'),
    ('Lord Serchester','Generous'),
    ('Lord Serchester','Royal'),
    ('Lord Serchester','Royal'),
    ('Anonymous','Lavish'),
    ('Anonymous','Lavish'),
    ('Anonymous','Lavish'),
    ('Anonymous','Generous'),
    ('Anonymous','Lavish'),
    ('Anonymous','Royal'),
    ('Anonymous','Royal'),
    ('Anonymous','Lavish'),
    ('Anonymous','Royal'),
    ('Anonymous','Generous'),
    ('Joun-Anghir','Royal'),
    ('Anonymous','Royal'),
    ('Anonymous','Generous'),
    ('Anonymous','Royal'),
    ('Anonymous','Royal'),
    ('Anonymous','Royal'),
    ('Anonymous','Royal'),
    ('Anonymous','Lordly'),
    ('Senor de Rohan','Lavish'),
    ('Max Revent','Royal'),
    ('Anonymous','Lordly'),
    ('Senor de Rohan','Lavish'),
    ('Anonymous','Royal'),
    ('Anonymous','Generous'),
    ('Da Queen','Royal'),
    ('Da Queen','Royal'),
    ('Da Queen','Royal'),
    ('Da Queen','Lordly'),
    ('Anonymous','Royal'),
    ('Anonymous','Royal'),
    ('Da Queen','Royal'),
    ('Da Queen','Royal'),
    ('Da Queen','Royal'),
    ('Da Queen','Royal'),
    ('Anonymous','Lavish'),
    ('Da Queen','Royal'),
    ('Da Queen','Royal'),
    ('Anonymous','Generous'),
    ('Lord Serchester','Lordly'),
    ('Anonymous','Lordly'),
    ('Senor de Rohan','Lordly'),
    ('Anonymous','Royal'),
    ('Joun-Anghir','Royal'),
    ('Anonymous','Grand'),
    ('Thuban','Grand'),
    ('Anonymous','Generous'),
    ('Anonymous','Royal'),
    ('Anonymous','Royal'),
    ('Anonymous','Royal'),
    ('Dawn Rooster','Royal'),
    ('Anonymous','Royal'),
    ('Da Queen','Royal'),
    ('Da Queen','Royal'),
    ('National Guards','Generous'),
    ('Anonymous','Royal'),
    ('KBaron','Royal'),
    ('Anonymous','Lordly'),
    ('FireCastle','Grand'),
    ('Da Queen','Royal'),
    ('Da Queen','Royal'),
    ('Anonymous','Lavish'),
    ('Dark Phoenix','Generous'),
    ('Anonymous','Generous'),
    ('King Terry','Generous'),
    ('Anonymous','Lordly'),
    ('MalvaHadita','Royal'),
    ('Anonymous','Royal'),
    ('Anonymous','Lordly'),
    ('KBaron','Royal'),
    ('KBaron','Royal'),
    ('Anonymous','Royal'),
    ('Anonymous','Lavish'),
    ('Joun-Anghir','Royal'),
    ('Joun-Anghir','Royal'),
    ('Anonymous','Lavish'),
    ('Kikin Mx','Lavish'),
    ('Max Revent','Royal'),
    ('KBaron','Royal');
INSERT INTO gifts VALUES
    ('National Guards','Generous'),
    ('Anonymous','Royal'),
    ('Anonymous','Lavish'),
    ('IamRomDawn','Grand'),
    ('Ave Fenix','Lordly'),
    ('Ave Fenix','Generous'),
    ('Anonymous','Generous'),
    ('Anonymous','Generous'),
    ('Anonymous','Generous'),
    ('IamRomDawn','Royal'),
    ('Anonymous','Royal'),
    ('Anonymous','Lordly'),
    ('Leonidas1980','Royal'),
    ('IamRomDawn','Royal'),
    ('KBaron','Royal'),
    ('KBaron','Royal'),
    ('KBaron','Royal'),
    ('KBaron','Royal'),
    ('KBaron','Royal'),
    ('Lady Leopard','Generous'),
    ('KBaron','Royal'),
    ('KBaron','Royal'),
    ('Shake and Bake','Royal'),
    ('Shake and Bake','Lordly'),
    ('Shake and Bake','Royal'),
    ('King Terry','Generous'),
    ('KBaron','Royal'),
    ('Anonymous','Royal'),
    ('Lady Leopard','Generous'),
    ('Subetai','Generous'),
    ('Leon19','Lavish'),
    ('KBaron','Royal'),
    ('KBaron','Royal'),
    ('SLP Alpha','Lordly'),
    ('KBaron','Lordly'),
    ('KBaron','Royal'),
    ('KBaron','Royal'),
    ('KBaron','Lavish'),
    ('Anonymous','Royal'),
    ('IamRomDawn','Royal'),
    ('Lady Leopard','Generous'),
    ('National Guards','Generous'),
    ('IamRomDawn','Royal'),
    ('Anonymous','Generous'),
    ('KBaron','Royal'),
    ('Anonymous','Grand'),
    ('Anonymous','Royal'),
    ('KBaron','Royal'),
    ('KBaron','Royal'),
    ('KBaron','Lavish'),
    ('Anonymous','Lavish'),
    ('Anonymous','Grand'),
    ('Anonymous','Generous'),
    ('Anonymous','Lavish'),
    ('Anonymous','Lavish'),
    ('Kikin Mx','Generous'),
    ('xxThanosxx','Royal'),
    ('IamRomDawn','Lavish'),
    ('Kikin Mx','Generous'),
    ('Anonymous','Royal'),
    ('FireCastle','Lordly'),
    ('KBaron','Lordly'),
    ('KBaron','Royal'),
    ('FireCastle','Royal'),
    ('KBaron','Royal'),
    ('KBaron','Royal'),
    ('KBaron','Royal'),
    ('KBaron','Royal'),
    ('Anonymous','Royal'),
    ('Anonymous','Royal'),
    ('House Ginger','Generous'),
    ('Anonymous','Generous'),
    ('Anonymous','Lordly'),
    ('IamRomDawn','Generous'),
    ('KBaron','Royal'),
    ('IamRomDawn','Lavish'),
    ('KBaron','Royal'),
    ('KBaron','Royal'),
    ('KBaron','Royal'),
    ('Da Queen','Lordly'),
    ('Da Queen','Royal'),
    ('Da Queen','Lordly'),
    ('Da Queen','Royal'),
    ('Da Queen','Lordly'),
    ('Da Queen','Lordly'),
    ('Da Queen','Royal'),
    ('Da Queen','Royal'),
    ('Da Queen','Royal'),
    ('Da Queen','Lordly'),
    ('Da Queen','Lordly'),
    ('Da Queen','Royal'),
    ('Da Queen','Royal'),
    ('Da Queen','Lordly'),
    ('Da Queen','Royal'),
    ('Shake and Bake','Royal'),
    ('KBaron','Royal'),
    ('KBaron','Royal'),
    ('KBaron','Royal'),
    ('Anonymous','Royal'),
    ('Anonymous','Lavish'),
    ('Anonymous','Grand'),
    ('Anonymous','Lordly'),
    ('Anonymous','Royal'),
    ('Anonymous','Royal'),
    ('Lord Serchester','Lordly'),
    ('Anonymous','Royal'),
    ('Anonymous','Royal'),
    ('Langolieri','Generous'),
    ('Anonymous','Royal'),
    ('Max Revent','Royal'),
    ('Anonymous','Royal'),
    ('Thuban','Generous'),
    ('Anonymous','Lordly'),
    ('Anonymous','Royal'),
    ('Ave Fenix','Royal'),
    ('House Ginger','Generous'),
    ('4 Eyed','Lordly'),
    ('4 Eyed','Lordly'),
    ('4 Eyed','Lordly'),
    ('4 Eyed','Lordly'),
    ('4 Eyed','Royal'),
    ('4 Eyed','Lordly'),
    ('4 Eyed','Royal'),
    ('4 Eyed','Royal'),
    ('4 Eyed','Royal'),
    ('KBaron','Lordly'),
    ('KBaron','Royal'),
    ('KBaron','Lordly'),
    ('KBaron','Lordly'),
    ('KBaron','Lordly'),
    ('KBaron','Lordly'),
    ('xxThanosxx','Lordly'),
    ('House Ginger','Lavish'),
    ('King Terry','Lavish'),
    ('Decimus Furious','Royal'),
    ('Lord Serchester','Royal'),
    ('Anonymous','Royal'),
    ('Anonymous','Royal'),
    ('SLP Alpha','Royal'),
    ('SLP Alpha','Royal'),
    ('Anonymous','Royal'),
    ('4 Eyed','Lavish'),
    ('4 Eyed','Generous'),
    ('4 Eyed','Royal'),
    ('4 Eyed','Royal'),
    ('4 Eyed','Royal'),
    ('4 Eyed','Royal'),
    ('4 Eyed','Generous'),
    ('Anonymous','Royal'),
    ('Anonymous','Royal'),
    ('Anonymous','Royal'),
    ('FireCastle','Royal'),
    ('Lord Serchester','Royal'),
    ('Anonymous','Lordly'),
    ('Anonymous','Royal'),
    ('Anonymous','Royal'),
    ('Anonymous','Royal'),
    ('Anonymous','Royal'),
    ('IamRomDawn','Royal'),
    ('Anonymous','Royal'),
    ('Decimus Furious','Generous'),
    ('FireCastle','Lavish'),
    ('Anonymous','Royal'),
    ('FireCastle','Royal'),
    ('IamRomDawn','Royal'),
    ('FireCastle','Royal'),
    ('Lord Serchester','Royal'),
    ('Anonymous','Generous'),
    ('KBaron','Royal'),
    ('FireCastle','Royal'),
    ('GuruStatus','Lordly'),
    ('FireCastle','Royal'),
    ('Lord Serchester','Royal'),
    ('Whoohor','Royal'),
    ('Ave Fenix','Royal'),
    ('Leonidas1980','Royal'),
    ('Anonymous','Grand'),
    ('Lord Serchester','Royal'),
    ('Anonymous','Royal'),
    ('Anonymous','Royal'),
    ('Anonymous','Generous'),
    ('Anonymous','Generous'),
    ('Kikin Mx','Lavish'),
    ('Uncle Bacon','Lordly'),
    ('Uncle Bacon','Royal'),
    ('Anonymous','Royal'),
    ('Uncle Bacon','Royal'),
    ('Uncle Bacon','Royal'),
    ('Anonymous','Royal'),
    ('Anonymous','Grand'),
    ('Leon19','Lavish'),
    ('Anonymous','Lordly'),
    ('Anonymous','Generous'),
    ('Anonymous','Lavish'),
    ('Anonymous','Lavish'),
    ('Anonymous','Royal'),
    ('Jay the Vile','Generous'),
    ('Anonymous','Royal'),
    ('FireCastle','Lordly'),
    ('Anonymous','Grand'),
    ('Anonymous','Lavish'),
    ('Anonymous','Generous'),
    ('Anonymous','Royal'),
    ('Senor de Rohan','Generous'),
    ('Anonymous','Generous'),
    ('Anonymous','Grand'),
    ('Anonymous','Royal'),
    ('3 eyed Erin','Generous'),
    ('Anonymous','Generous'),
    ('Kikin Mx','Lavish'),
    ('Kikin Mx','Lordly'),
    ('Anonymous','Generous'),
    ('Anonymous','Grand'),
    ('Anonymous','Royal'),
    ('Kikin Mx','Generous'),
    ('Anonymous','Lavish'),
    ('Anonymous','Lavish'),
    ('GuruStatus','Generous'),
    ('Anonymous','Royal'),
    ('Anonymous','Grand'),
    ('Anonymous','Generous'),
    ('IamRomDawn','Lavish'),
    ('Whoohor','Grand'),
    ('Anonymous','Generous'),
    ('Anonymous','Generous'),
    ('Anonymous','Generous'),
    ('Anonymous','Royal'),
    ('Anonymous','Royal'),
    ('Anonymous','Lordly'),
    ('Anonymous','Generous'),
    ('Anonymous','Royal'),
    ('KBaron','Royal'),
    ('KBaron','Royal'),
    ('KBaron','Royal'),
    ('Anonymous','Generous'),
    ('Jon Snow23','Lordly'),
    ('Anonymous','Lordly'),
    ('Anonymous','Lordly'),
    ('Thuban','Generous'),
    ('Kikin Mx','Generous'),
    ('Anonymous','Royal'),
    ('Anonymous','Generous'),
    ('Anonymous','Royal'),
    ('FireCastle','Royal'),
    ('Anonymous','Lordly'),
    ('Anonymous','Royal'),
    ('Anonymous','Lordly'),
    ('Decimus Furious','Royal'),
    ('Anonymous','Grand'),
    ('IamRomDawn','Lordly');
INSERT INTO gifts VALUES
    ('Anonymous','Generous'),
    ('Anonymous','Royal'),
    ('Anonymous','Royal'),
    ('Anonymous','Lordly'),
    ('Anonymous','Royal'),
    ('Anonymous','Royal'),
    ('FireCastle','Lordly'),
    ('Anonymous','Lordly'),
    ('Jon Snow23','Generous'),
    ('Anonymous','Royal'),
    ('FireCastle','Royal'),
    ('FireCastle','Royal'),
    ('FireCastle','Royal'),
    ('Anonymous','Generous'),
    ('FireCastle','Lordly'),
    ('Anonymous','Generous'),
    ('Anonymous','Royal'),
    ('The White','Grand'),
    ('Lord Serchester','Royal'),
    ('Anonymous','Lavish'),
    ('Lord Serchester','Royal'),
    ('Kikin Mx','Generous'),
    ('Anonymous','Lavish'),
    ('Lord Serchester','Royal'),
    ('Anonymous','Royal'),
    ('Anonymous','Lavish'),
    ('Anonymous','Generous'),
    ('FireCastle','Lordly'),
    ('Anonymous','Generous'),
    ('Anonymous','Generous'),
    ('Anonymous','Grand'),
    ('Anonymous','Lavish'),
    ('Lord Serchester','Royal'),
    ('Anonymous','Royal'),
    ('SLP Alpha','Royal'),
    ('Anonymous','Generous'),
    ('Anonymous','Lordly'),
    ('Anonymous','Royal'),
    ('Anonymous','Lordly'),
    ('Anonymous','Generous'),
    ('Leonidas1980','Royal'),
    ('Anonymous','Lavish'),
    ('Anonymous','Generous'),
    ('Anonymous','Royal'),
    ('FireCastle','Grand'),
    ('Anonymous','Royal'),
    ('Anonymous','Lavish'),
    ('Anonymous','Royal'),
    ('Anonymous','Royal'),
    ('Anonymous','Lavish'),
    ('Den of Drogo','Lordly'),
    ('Anonymous','Generous'),
    ('Anonymous','Lordly'),
    ('Anonymous','Lavish'),
    ('Anonymous','Lavish'),
    ('Anonymous','Generous'),
    ('Anonymous','Generous'),
    ('3 eyed Erin','Generous'),
    ('Thuban','Generous'),
    ('Anonymous','Generous'),
    ('Anonymous','Generous'),
    ('Anonymous','Royal'),
    ('Anonymous','Royal'),
    ('Anonymous','Royal'),
    ('IamRomDawn','Royal'),
    ('Anonymous','Royal'),
    ('Anonymous','Generous'),
    ('FireCastle','Lordly'),
    ('FireCastle','Royal'),
    ('Anonymous','Lavish'),
    ('Anonymous','Generous'),
    ('Ebony Maw','Generous'),
    ('Anonymous','Generous'),
    ('Anonymous','Royal'),
    ('Kikin Mx','Lordly'),
    ('Anonymous','Generous'),
    ('Anonymous','Generous'),
    ('Anonymous','Generous'),
    ('King Terry','Generous'),
    ('Anonymous','Royal'),
    ('FireCastle','Grand'),
    ('FireCastle','Grand'),
    ('Anonymous','Generous'),
    ('Anonymous','Lordly'),
    ('3 Eyed Erin','Generous'),
    ('Anonymous','Royal'),
    ('Langolieri','Generous'),
    ('KBaron','Royal'),
    ('FireCastle','Generous'),
    ('KBaron','Royal'),
    ('FireCastle','Generous'),
    ('Anonymous','Generous'),
    ('Anonymous','Grand'),
    ('Kikin Mx','Generous'),
    ('Kikin Mx','Generous'),
    ('FireCastle','Royal'),
    ('Anonymous','Royal'),
    ('IamRomDawn','Lordly'),
    ('Anonymous','Grand'),
    ('Anonymous','Generous'),
    ('Anonymous','Royal'),
    ('Anonymous','Generous'),
    ('Anonymous','Royal'),
    ('Anonymous','Royal'),
    ('SLP Alpha','Grand'),
    ('Grekkon','Lavish'),
    ('Anonymous','Royal'),
    ('Senor de Rohan','Generous'),
    ('Anonymous','Royal'),
    ('Anonymous','Royal'),
    ('Anonymous','Generous'),
    ('Anonymous','Grand'),
    ('Anonymous','Royal'),
    ('Anonymous','Lordly'),
    ('Anonymous','Lordly'),
    ('Anonymous','Lavish'),
    ('FireCastle','Generous'),
    ('Anonymous','Royal'),
    ('Anonymous','Royal'),
    ('Anonymous','Grand'),
    ('Lady W-Star','Lordly'),
    ('Lady W-Star','Royal'),
    ('Anonymous','Lordly'),
    ('Langolieri','Lordly'),
    ('IamRomDawn','Royal'),
    ('Anonymous','Grand'),
    ('Dawn Rooster','Generous'),
    ('Anonymous','Generous'),
    ('Lady W-Star','Royal'),
    ('Anonymous','Royal'),
    ('SLP Alpha','Generous'),
    ('FireCastle','Generous'),
    ('Anonymous','Royal'),
    ('Anonymous','Generous'),
    ('Anonymous','Generous'),
    ('Anonymous','Generous'),
    ('Decimus Furious','Royal'),
    ('FireCastle','Royal'),
    ('FireCastle','Royal'),
    ('FireCastle','Generous'),
    ('FireCastle','Royal'),
    ('FireCastle','Generous'),
    ('King Terry','Generous'),
    ('Anonymous','Royal'),
    ('Anonymous','Generous'),
    ('Anonymous','Lordly'),
    ('Anonymous','Generous'),
    ('Flamberge','Generous'),
    ('Anonymous','Royal'),
    ('IamRomDawn','Generous'),
    ('Anonymous','Royal'),
    ('Anonymous','Royal'),
    ('Anonymous','Royal'),
    ('Anonymous','Royal'),
    ('FireCastle','Royal'),
    ('3 Eyed Erin','Grand'),
    ('Anonymous','Royal'),
    ('Anonymous','Royal'),
    ('Anonymous','Royal'),
    ('Anonymous','Royal'),
    ('Anonymous','Royal'),
    ('Anonymous','Royal'),
    ('Anonymous','Lordly'),
    ('Anonymous','Royal'),
    ('Anonymous','Lavish'),
    ('Anonymous','Royal'),
    ('Anonymous','Royal'),
    ('Anonymous','Royal'),
    ('Anonymous','Lavish'),
    ('King Terry','Lavish'),
    ('Anonymous','Lavish'),
    ('Anonymous','Royal'),
    ('Anonymous','Generous'),
    ('Anonymous','Generous'),
    ('Anonymous','Lavish'),
    ('Anonymous','Lavish'),
    ('Anonymous','Royal'),
    ('Anonymous','Generous'),
    ('Anonymous','Lavish'),
    ('Anonymous','Royal'),
    ('Aegon Targaryen','Grand'),
    ('Aegon Targaryen','Generous'),
    ('Senor de Rohan','Generous'),
    ('Anonymous','Generous'),
    ('Anonymous','Lordly'),
    ('Anonymous','Royal'),
    ('Anonymous','Royal'),
    ('Anonymous','Royal'),
    ('Anonymous','Royal'),
    ('Anonymous','Royal'),
    ('Anonymous','Royal'),
    ('Max Revent','Royal'),
    ('Anonymous','Royal'),
    ('Anonymous','Royal'),
    ('Anonymous','Royal'),
    ('Anonymous','Royal'),
    ('Anonymous','Royal'),
    ('Anonymous','Royal'),
    ('Lady wise','Humble'),
    ('KBaron','Royal'),
    ('KBaron','Royal'),
    ('Emmett','Lavish'),
    ('Aegon Targaryen','Lavish'),
    ('Kikin Mx','Grand'),
    ('Lady wise','Humble'),
    ('Lord Wise','Generous'),
    ('Lord Wise','Generous'),
    ('Lord Wise','Humble'),
    ('Anonymous','Humble'),
    ('Senor de Rohan','Lavish'),
    ('Anonymous','Generous'),
    ('Anonymous','Generous'),
    ('Anonymous','Lordly'),
    ('Anonymous','Royal'),
    ('Lady wise','Humble'),
    ('IamRomDawn','Lordly'),
    ('Decimus Furious','Lordly'),
    ('IamRomDawn','Grand'),
    ('Anonymous','Lavish'),
    ('Anonymous','Generous'),
    ('SLP Alpha','Royal'),
    ('Anonymous','Generous'),
    ('Anonymous','Royal'),
    ('Anonymous','Lavish'),
    ('Lady wise','Humble'),
    ('Anonymous','Lavish'),
    ('Kami_','Generous'),
    ('Lady wise','Humble'),
    ('Anonymous','Generous'),
    ('Anonymous','Lordly'),
    ('Ebony Maw','Generous'),
    ('Den of Drogo','Generous'),
    ('King Terry','Generous'),
    ('Lady wise','Humble'),
    ('MalvaHadita','Royal'),
    ('Anonymous','Royal'),
    ('Anonymous','Generous'),
    ('xxThanosxx','Generous'),
    ('Anonymous','Royal'),
    ('Aegon Targaryen','Lavish'),
    ('Lady wise','Humble'),
    ('KBaron','Royal'),
    ('KBaron','Royal'),
    ('KBaron','Royal'),
    ('Anonymous','Royal'),
    ('Lady Leopard','Lavish'),
    ('Phantom Phreak','Generous'),
    ('Phantom Phreak','Generous'),
    ('Max Revent','Royal'),
    ('Lady wise','Humble');
INSERT INTO gifts VALUES
    ('Anonymous','Generous'),
    ('Anonymous','Grand'),
    ('SLP Alpha','Royal'),
    ('Anonymous','Royal'),
    ('Anonymous','Royal'),
    ('Anonymous','Royal'),
    ('Anonymous','Royal'),
    ('The White','Royal'),
    ('Lady wise','Humble'),
    ('Decimus Furious','Generous'),
    ('Lady wise','Humble'),
    ('Lady wise','Humble'),
    ('King Terry','Generous'),
    ('Den of Drogo','Generous'),
    ('Anonymous','Royal'),
    ('Kami_','Lordly'),
    ('Anonymous','Royal'),
    ('Anonymous','Royal'),
    ('Anonymous','Royal'),
    ('Anonymous','Royal'),
    ('3 Eyed Erin','Generous'),
    ('Anonymous','Lavish'),
    ('Anonymous','Royal'),
    ('Lady Wise','Humble'),
    ('Anonymous','Generous'),
    ('Anonymous','Generous'),
    ('Anonymous','Generous'),
    ('Anonymous','Generous'),
    ('Anonymous','Generous'),
    ('Anonymous','Generous'),
    ('Anonymous','Generous'),
    ('Anonymous','Generous'),
    ('Anonymous','Generous'),
    ('Anonymous','Generous'),
    ('Anonymous','Generous'),
    ('Anonymous','Generous'),
    ('Anonymous','Generous'),
    ('Anonymous','Generous'),
    ('Anonymous','Generous'),
    ('Anonymous','Generous'),
    ('Anonymous','Generous'),
    ('Anonymous','Generous'),
    ('Anonymous','Generous'),
    ('Anonymous','Generous'),
    ('Anonymous','Generous'),
    ('Anonymous','Generous'),
    ('Anonymous','Generous'),
    ('Anonymous','Generous'),
    ('Lady Wise','Humble'),
    ('Lady Wise','Humble'),
    ('Anonymous','Generous'),
    ('Anonymous','Lavish'),
    ('Anonymous','Grand'),
    ('Anonymous','Generous'),
    ('Phantom Phreak','Generous'),
    ('Phantom Phreak','Generous'),
    ('Anonymous','Royal'),
    ('Anonymous','Royal'),
    ('Anonymous','Royal'),
    ('Anonymous','Lordly'),
    ('Anonymous','Generous'),
    ('Anonymous','Royal'),
    ('Anonymous','Lordly'),
    ('Anonymous','Royal'),
    ('Anonymous','Generous'),
    ('Anonymous','Royal'),
    ('GuruStatus','Royal'),
    ('Anonymous','Lordly'),
    ('Anonymous','Royal'),
    ('Max Revent','Royal'),
    ('Anonymous','Lordly'),
    ('KBaron','Royal'),
    ('KBaron','Royal'),
    ('Anonymous','Royal'),
    ('Anonymous','Lordly'),
    ('Anonymous','Royal'),
    ('Anonymous','Royal'),
    ('Anonymous','Royal'),
    ('Anonymous','Royal'),
    ('KBaron','Royal'),
    ('KBaron','Royal'),
    ('Anonymous','Lavish'),
    ('KBaron','Lordly'),
    ('Anonymous','Generous'),
    ('Max Revent','Royal'),
    ('KBaron','Lordly'),
    ('KBaron','Lordly'),
    ('KBaron','Lordly'),
    ('Anonymous','Lavish'),
    ('KBaron','Royal'),
    ('Anonymous','Royal'),
    ('Anonymous','Royal'),
    ('Anonymous','Lavish'),
    ('Anonymous','Royal'),
    ('Anonymous','Lordly'),
    ('Anonymous','Royal'),
    ('Anonymous','Royal'),
    ('Anonymous','Royal'),
    ('Anonymous','Royal'),
    ('Anonymous','Generous'),
    ('Anonymous','Royal'),
    ('Anonymous','Royal'),
    ('Anonymous','Royal'),
    ('Anonymous','Royal'),
    ('Emmett','Generous'),
    ('Emmett','Generous'),
    ('Anonymous','Lavish'),
    ('Anonymous','Generous'),
    ('Anonymous','Royal'),
    ('Anonymous','Generous'),
    ('Lady Leopard','Lavish'),
    ('Phantom Phreak','Generous'),
    ('Phantom Phreak','Lavish'),
    ('KBaron','Lordly'),
    ('Anonymous','Lavish'),
    ('King Terry','Lavish'),
    ('Anonymous','Royal'),
    ('Anonymous','Lordly'),
    ('Anonymous','Royal'),
    ('Anonymous','Royal'),
    ('Anonymous','Generous'),
    ('Anonymous','Lavish'),
    ('Anonymous','Lavish'),
    ('Anonymous','Generous'),
    ('Anonymous','Lavish'),
    ('Anonymous','Lavish'),
    ('Whoohor','Generous'),
    ('Anonymous','Royal'),
    ('Uncle Bacon','Royal'),
    ('Anonymous','Lavish'),
    ('Anonymous','Generous'),
    ('Anonymous','Generous'),
    ('Emmett','Generous'),
    ('Emmett','Lavish'),
    ('Emmett','Lavish'),
    ('Emmett','Generous'),
    ('IamRomDawn','Lordly'),
    ('Whoohor','Generous'),
    ('Anonymous','Generous'),
    ('Anonymous','Generous'),
    ('Anonymous','Lavish'),
    ('Anonymous','Generous'),
    ('Anonymous','Generous'),
    ('Anonymous','Lordly'),
    ('Anonymous','Generous'),
    ('Anonymous','Generous'),
    ('Anonymous','Lordly'),
    ('Anonymous','Generous'),
    ('Anonymous','Generous'),
    ('Anonymous','Lavish'),
    ('Anonymous','Generous'),
    ('Anonymous','Generous'),
    ('Anonymous','Grand'),
    ('Emmett','Lavish'),
    ('Emmett','Lavish'),
    ('Emmett','Royal'),
    ('Anonymous','Grand'),
    ('Anonymous','Lavish'),
    ('Max Revent','Royal'),
    ('Jon Snow23','Lordly'),
    ('Anonymous','Royal'),
    ('Phantom Phreak','Grand'),
    ('Phantom Phreak','Lavish'),
    ('Jon Snow23','Generous'),
    ('Den of Drogo','Lavish'),
    ('Anonymous','Royal'),
    ('Anonymous','Generous'),
    ('Anonymous','Generous'),
    ('Anonymous','Royal'),
    ('Anonymous','Royal'),
    ('Anonymous','Royal'),
    ('Anonymous','Royal'),
    ('Anonymous','Royal'),
    ('Anonymous','Royal'),
    ('Anonymous','Royal'),
    ('Anonymous','Royal'),
    ('Anonymous','Lordly'),
    ('Anonymous','Royal'),
    ('Anonymous','Lordly'),
    ('Anonymous','Lordly'),
    ('Anonymous','Lordly'),
    ('Anonymous','Royal'),
    ('Anonymous','Grand'),
    ('Anonymous','Lordly'),
    ('Anonymous','Grand'),
    ('Langolieri','Generous'),
    ('Anonymous','Royal'),
    ('Anonymous','Lavish'),
    ('Anonymous','Lavish'),
    ('Max Revent','Royal'),
    ('Anonymous','Lavish'),
    ('Emmett','Grand'),
    ('Emmett','Generous'),
    ('Emmett','Generous'),
    ('Emmett','Lavish'),
    ('Decimus Furious','Lavish'),
    ('Anonymous','Generous'),
    ('Anonymous','Royal'),
    ('Anonymous','Generous'),
    ('Anonymous','Generous'),
    ('Anonymous','Lavish'),
    ('Anonymous','Lavish'),
    ('Emmett','Grand'),
    ('Emmett','Grand'),
    ('Emmett','Grand'),
    ('Anonymous','Generous'),
    ('Anonymous','Lavish'),
    ('Anonymous','Generous'),
    ('Anonymous','Generous'),
    ('Anonymous','Generous'),
    ('Anonymous','Generous'),
    ('Anonymous','Royal'),
    ('Anonymous','Generous'),
    ('Aegon Targaryen','Generous'),
    ('Emmett','Generous'),
    ('Aegon Targaryen','Lavish'),
    ('Emmett','Lavish'),
    ('Emmett','Generous'),
    ('Emmett','Grand'),
    ('GuruStatus','Royal'),
    ('King Terry','Generous'),
    ('King Terry','Lavish'),
    ('Anonymous','Lordly'),
    ('Anonymous','Grand'),
    ('Anonymous','Grand'),
    ('Anonymous','Royal'),
    ('IamRomDawn','Generous'),
    ('Anonymous','Lordly'),
    ('3 Eyed Erin','Lavish'),
    ('Den of Drogo','Generous'),
    ('The White','Lavish'),
    ('Anonymous','Royal'),
    ('Emmett','Lavish'),
    ('Emmett','Generous'),
    ('Anonymous','Royal'),
    ('Anonymous','Royal'),
    ('Anonymous','Royal'),
    ('Anonymous','Royal'),
    ('Anonymous','Royal'),
    ('Anonymous','Royal'),
    ('Anonymous','Royal'),
    ('Anonymous','Royal'),
    ('Anonymous','Royal'),
    ('Anonymous','Royal'),
    ('Anonymous','Royal'),
    ('Anonymous','Royal'),
    ('Anonymous','Royal'),
    ('Anonymous','Royal'),
    ('Anonymous','Lavish'),
    ('Anonymous','Lordly');
INSERT INTO gifts VALUES
    ('Anonymous','Lordly'),
    ('Anonymous','Royal'),
    ('Anonymous','Royal'),
    ('Max Revent','Royal'),
    ('Emmett','Lordly'),
    ('Unknown','Generous'),
    ('Anonymous','Royal'),
    ('Emmett','Lavish'),
    ('Emmett','Generous'),
    ('Anonymous','Generous'),
    ('Anonymous','Lavish'),
    ('Anonymous','Lordly'),
    ('Anonymous','Royal'),
    ('Anonymous','Royal'),
    ('Anonymous','Royal'),
    ('Anonymous','Royal'),
    ('Anonymous','Royal'),
    ('Anonymous','Royal'),
    ('Langolieri','Generous'),
    ('Anonymous','Royal'),
    ('Anonymous','Lavish'),
    ('King Terry','Generous'),
    ('King Terry','Lavish'),
    ('Anonymous','Lavish'),
    ('Anonymous','Generous'),
    ('Anonymous','Royal'),
    ('Anonymous','Royal'),
    ('Emmett','Generous'),
    ('Vaedor','Royal'),
    ('xxThanosxx','Generous'),
    ('Anonymous','Lavish'),
    ('Anonymous','Royal'),
    ('Anonymous','Royal'),
    ('Anonymous','Royal'),
    ('Emmett','Grand'),
    ('Ebony Maw','Generous'),
    ('Anonymous','Generous'),
    ('Anonymous','Lavish'),
    ('Anonymous','Lordly'),
    ('Anonymous','Lavish'),
    ('Anonymous','Generous'),
    ('Anonymous','Generous'),
    ('Anonymous','Royal'),
    ('Anonymous','Lavish'),
    ('Anonymous','Lavish'),
    ('Anonymous','Generous'),
    ('Anonymous','Royal'),
    ('Anonymous','Generous'),
    ('3 Eyed Erin','Generous'),
    ('3 Eyed Erin','Lavish'),
    ('Anonymous','Generous'),
    ('Anonymous','Lavish'),
    ('dark Phoenix','Lavish'),
    ('Anonymous','Royal'),
    ('King Terry','Grand'),
    ('Anonymous','Lavish'),
    ('Anonymous','Generous'),
    ('Grekkon','Lavish'),
    ('Emmett','Grand');
